#!/usr/bin/env bash
# Transfers a file from our client to a server:
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ "${#}" -eq 4 ]
then
    PATH_TO_FILE="${1}"
    IP="${2}"
    USERNAME="${3}"
    PATH_TO_SSH_KEY="${4}"

    scp -o StrictHostKeyChecking=no -i "${PATH_TO_SSH_KEY}" "${PATH_TO_FILE}" "${USERNAME}"@"${IP}":~/
else
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
